name: couteau_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.1.7
  font_awesome_flutter: '>= 4.7.0'
  flutter_html: ^3.0.0-beta.2  # Actualizado a la versión beta
  html_unescape: ^2.0.0
  flutter_math_fork: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
